version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install awscli
  build:
    commands:
      - CF_BUCKET=txxx
      - CF_STACK=InfraCoreStack
      - echo Syncing CloudFormation nested stack code to S3...
      - aws s3 sync CloudFormation/NestedStacks s3://$CF_BUCKET/$CF_STACK --delete
artifacts:
  files:
    - '**/*'