version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install awscli
  build:
    commands:
      # TODO - Parameter@Single source of truth! Use SSM:Paramter to stote common templates.
      - cf_bucket=iris-infrapipeline-templatesxj
      - templatepath="CloudFormation/nestedstacks"
      - cf_stack=InfraCoreStack
      - echo Syncing CloudFormation Nested stack code to S3 bucket...
      - aws s3 sync $templatepath s3://$cf_bucket/$cf_stack --delete
artifacts:
  files:
    - '**/*'