version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install awscli
  build:
    commands:
      - LINK=$(aws cloudformation describe-change-set --change-set-name my-change-set-name --stack-name my-stack-name | jq -r '.ChangeSetId, .StackName')
      - echo $LINK
      - aws ssm put-parameter --name MyLinkParameter --type String --value "${LINK}"  --overwrite
artifacts:
  files:
    - '**/*'