version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install awscli
  build:
    commands:
      - CHANGESETNAME=InfraCoreChangeset
      - STACKSETNAME=InfraCoreStack
      - CHANGESETID=$(aws cloudformation describe-change-set --change-set-name $CHANGESETNAME  --stack-name $STACKSETNAME | jq -r '.ChangeSetId')
      - STACKSETID=$(aws cloudformation describe-change-set --change-set-name $CHANGESETNAME  --stack-name $STACKSETNAME | jq -r '.StackId')
      - LINK="https://console.aws.amazon.com/cloudformation/home?region=ca-central-1#/stacks/changesets/changesetdetail?changeSetId=$CHANGESETID&stackId=$STACKSETID"
      - echo Changeset Review Link - $LINK
      - aws ssm put-parameter --name MyLinkParameter --type String --value "${LINK}"  --overwrite
artifacts:
  files:
    - '**/*'