---
Parameters:
  EC2InstanceType:
    Type: String
    Description: EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  EC2ImageId:
    Type: String
    Description: EC2 image ID

AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: file:/./NestedStacks/ec2.yml
      Parameters:
        InstanceType: !Ref EC2InstanceType
        ImageId: !Ref EC2ImageId





    
