---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EC2InstanceType:
    Type: String
    Description: EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  EC2ImageId:
    Type: String
    Description: EC2 image ID

Resources:
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/txxx/ec2.yml
      Parameters:
        EC2InstanceType: !Ref EC2InstanceType
        EC2ImageId: !Ref EC2ImageId
