---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Description: Deployment Environment
    AllowedValues:
      - "prod"
      - "nonprod"
  CoreStackName:
    Type: String
  CFBucket:
    Type: String
    Description: The name of the S3 bucket where the CloudFormation template is located.
  VpcCidrBlock:
    Type: String
    Description: VPC CIDR Block 
Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:  !Sub "https://s3.amazonaws.com/iris-infrapipeline-templatesxj/InfraCoreStack/${AWS::StackName}.yml"

    #    'Fn::Join': ["", ["https://s3.amazonaws.com/", !Ref CFBucket, "/", !Ref CoreStackName, "/", !Ref "AWS::StackName", ".yml"]]
    #    'Fn::Join': [ "", ["CloudFormationRole", "-", !Ref 'AWS::StackName']]

#      TemplateURL: https://s3.amazonaws.com/iris-infrapipeline-templatesxj/InfraCoreStack/VpcStack.yml
      Parameters:
        VpcCidrBlock: !Ref VpcCidrBlock
        Environment: !Ref Environment